### PR TITLE
compile.scm serialization: support smaller sizes, in particular 32bit compat

### LINKED ISSUE #52: Support i686?
Since I pushed camlboot to Guix, we kinda need to support the platform it supports (well, I can also fix that by not using camlboot on i686). Here is the error I get (see https://ci.guix.gnu.org/build/18557/log/raw):

```
mkdir -p lex/
../../ocaml-src/byterun/ocamlrun lex.boot.byte ../../ocaml-src/lex/lexer.mll -o lex/lexer.ml
Fatal error: exception Failure("input_value: object too large to be read back on a 32-bit platform")
make[1]: *** [Makefile:28: lex/lexer.ml] Error 2
```

Is this an issue with `lex.boot.byte` (because we maybe only create bytecode for 64 bit architectures), or with `lexer.mll` (because maybe it creates huge objects)?

### PR DESCRIPTION
**Pull request by gasche**
This should hopefully fix #52. I am not sure, though, as I don't have a 32bit machine at hand to test easily. (And I'm too lazy to setup qemu for this.)

Context: the compiler needs to use OCaml's serialization format for the constant table and debug information. The serialization format is "dynamically typed", in that before each value comes a header that gives the format of the value. In particular, on 32 bit machines an OCaml integer will come with the header CODE_INT32, followed by a 32bits integer. 64bit machines will also use CODE_INT32 for integers that fit within the 32bit range, and CODE_INT64 when it does not (followed by an 64bits integer). Other size classes are supported (int16, int8, and an even smaller "small int" class whose value is encoded in the code word itself), to give a compact encoding.

The previous version of the encoder would always use the CODE_INT64 encoding. This PR implements logic to use the CODE_INT32 encoding for in-32bit-range inputs, and also the "small int" class for compactness. This means that, as long as the serializer only encounters 32bit-compatible inputs, the produced object should also be 32bit-compatible. (But there is no dynamic check to enforce this, so it could also emit incompatible information in theory, for very large constant tables or debug information.)

### CODE REVIEW

**Comment by gasche** [comment]
Note: one indirect benefit of the change is that it makes the bytecode files noticeably more compact, typically a 40% reduction.

**Comment by roptat** [comment]
I don't have a 32 bit machine, but it's possible to test it with guix easily:

```
guix build camlboot -s i686-linux
```

fails with the reported error. I changed the recipe a bit to test your changes. The build is not finished, but went further than before (currently running interp for the first time), so that's clearly better, thank you!

**Comment by gasche** [comment]
I would feel better if someone reviewed this PR, and I think realistically it should be @Ekdohibs (this is not-so-simple code that he wrote in the first place). Given his reduced-availabilities, this suggests that we have time to wait for your build to finish :-)

**Comment by gasche** [comment]
Looking at the PR again: I realize now that something is missing that I was planning to implement, and I don't understand why a 32bit build would work better without it. OCaml has two different header formats for marshalled metadata (I learned this stuff on the fly while preparing this PR), one for 64bit systems and one that is compatible with both 32bit and 64bit (but has 32bit-restricted size limits). I was planning to include the logic to generate either of those depending on whether the 32bit-style header fits, but I forgot to include it in the final PR!

My understanding of the runtime is that the current PR *should not* work on a 32bit system. But then I may be wrong about that. Or it may be the case that `guix build camlboot -s i686-linux` is a hybrid system that expects 32bit-pointers but somehow supports some 64bit things just fine, so it fails to fail as I would expect.

In any case: implementing the alternative header format is not much work, and I can test the result on my 64bit machine, so I'm going to do that just now.

**Comment by gasche** [comment]
> implementing the alternative header format is not much work, and I can test the result on my 64bit machine, so I'm going to do that just now.

done and pushed.

**Comment by roptat** [comment]
Oh, I actually forgot to use the `-s i686-linux` flag when building, so it was building the 64 bits version. With your new commit, I'm able to go further in the build, but it fails at the first run of `interp`:

```
./interp -nopervasives -nostdlib -w -20-21 -I ../../interpreter -c stdopt.mli
Fatal error: exception Failure("input_value: integer too large")
```

**Comment by gasche** [comment]
I found the culprit: @Ekdohibs.

```
(* interpeter/conf.ml *)
let tracearg_from = 75000_000000
```

Let me migrate the tracing machinery to `Int64` for portability, and see where we are then.

**Comment by gasche** [comment]
Done. @roptat, when you have time, a new 32bit test would be nice.

**Comment by Ekdohibs** [comment]
I'm not sure converting to `Int64` is a good idea. The only reason this value was so large is because it was `75000` before and I wanted to make it larger than the maximum value encountered in the program. If converting to `Int64`, we lose even more performance when tracing...

**Comment by gasche** [comment]
Ah, I really thought this was somehow the number of interpretation steps of the standard library or something. Are you sure there is no risk of 32bit overflow of this trace counter?

**Comment by Ekdohibs** [comment]
Not sure - it's the number of calls in the program. So, for large enough programs, it could indeed overflow.

**Comment by gasche** [comment]
(I sent an email to complain politely about our Makefiles.)

**Comment by gasche** [comment]
I think that we should:

1. check whether the counter overflows a 32bit-integer
2. measure the overhead of using an int64 counter

Assuming that we do overflow (1), I think using an `int` counter is a bad idea. If the overhead (2) is reasonable, let's use an `int64`, or otherwise drop the counter completely.

**Comment by roptat** [comment]
So I tried the branch again, and it's going a bit further, but not too much. It seems to be confused about which architecture it's building for:

```
File "stdopt_exit.ml", line 1:
Error: Assembler error, input left in file /tmp/guix-build-camlboot-0.0.0-0.3623d99.drv-0/camlasm21aa9b.s
make[1]: *** [Makefile:76: stdopt_exit.cmx] Error 2
make[1]: *** Waiting for unfinished jobs....
/tmp/guix-build-camlboot-0.0.0-0.3623d99.drv-0/camlasm3e4cee.s: Assembler messages:
/tmp/guix-build-camlboot-0.0.0-0.3623d99.drv-0/camlasm3e4cee.s:34: Error: bad register name `%rsp'
/tmp/guix-build-camlboot-0.0.0-0.3623d99.drv-0/camlasm3e4cee.s:37: Error: bad register name `%rip)'
/tmp/guix-build-camlboot-0.0.0-0.3623d99.drv-0/camlasm3e4cee.s:38: Error: bad register name `%rax'
/tmp/guix-build-camlboot-0.0.0-0.3623d99.drv-0/camlasm3e4cee.s:39: Error: bad register name `%rbx)'
/tmp/guix-build-camlboot-0.0.0-0.3623d99.drv-0/camlasm3e4cee.s:40: Error: bad register name `%rdi'
/tmp/guix-build-camlboot-0.0.0-0.3623d99.drv-0/camlasm3e4cee.s:42: Error: bad register name `%rax'
/tmp/guix-build-camlboot-0.0.0-0.3623d99.drv-0/camlasm3e4cee.s:43: Error: bad register name `%rip)'
/tmp/guix-build-camlboot-0.0.0-0.3623d99.drv-0/camlasm3e4cee.s:44: Error: bad register name `%rax'
/tmp/guix-build-camlboot-0.0.0-0.3623d99.drv-0/camlasm3e4cee.s:45: Error: bad register name `%rbx)'
/tmp/guix-build-camlboot-0.0.0-0.3623d99.drv-0/camlasm3e4cee.s:46: Error: bad register name `%rdi'
/tmp/guix-build-camlboot-0.0.0-0.3623d99.drv-0/camlasm3e4cee.s:48: Error: bad register name `%rax'
/tmp/guix-build-camlboot-0.0.0-0.3623d99.drv-0/camlasm3e4cee.s:49: Error: bad register name `%rip)'
/tmp/guix-build-camlboot-0.0.0-0.3623d99.drv-0/camlasm3e4cee.s:50: Error: bad register name `%rax'
/tmp/guix-build-camlboot-0.0.0-0.3623d99.drv-0/camlasm3e4cee.s:51: Error: bad register name `%rbx)'
/tmp/guix-build-camlboot-0.0.0-0.3623d99.drv-0/camlasm3e4cee.s:52: Error: bad register name `%rdi'
/tmp/guix-build-camlboot-0.0.0-0.3623d99.drv-0/camlasm3e4cee.s:54: Error: bad register name `%rax'
/tmp/guix-build-camlboot-0.0.0-0.3623d99.drv-0/camlasm3e4cee.s:55: Error: bad register name `%rax'
/tmp/guix-build-camlboot-0.0.0-0.3623d99.drv-0/camlasm3e4cee.s:56: Error: bad register name `%rsp'
```

We get the same kind of error on aarch64 (64-bit arm): https://ci.guix.gnu.org/build/4892/log/raw

**Comment by roptat** [comment]
By the way, my previous message meant that, even though it doesn't fix the whole issue, it does help, so I think it's fine to merge :). The remaining issue is probably related to instruction selection, inside ocamlopt.

**Comment by gasche** [comment]
I plan to rebase this against master and then merge.

**Pull request merged**
