### PR TITLE
guile compile.scm lib.ml --open Lib main.ml

### PR DESCRIPTION
**Pull request by gasche**
A proposal for the use-case of @Ekdohibs in https://github.com/Ekdohibs/camlboot/pull/25#issuecomment-743416210 .

### CODE REVIEW

**Review by Ekdohibs — APPROVED** [review]
Code seems good! However, I am not sure about the single-dash name for a long argument: could we call it `--open` maybe?

**Comment by gasche** [comment]
I'm happy to go with `--open`; `-open` has the advantage of being the name used by `ocamlc`, but then the semantics is slightly different in multifile scenarios anyway, so let's go with more standard usage of option names.

**Comment by gasche** [comment]
I rebased the PR to use `--open`.

**Comment by Ekdohibs** [comment]
Ah yes, I'd forgotten that `ocamlc` used non-standard naming for the flags. Anyway, `--open` is still the best, I think.

**Pull request merged**
