### PR TITLE
Lowering

### PR DESCRIPTION
**Pull request by gasche**
This is an in-progress branch on top of #9 (so #9 should be reviewed first and this one is to give an idea of what the next batch of changes will look like). It introduces a "lowering" pass before actual code generation. It may not look obvious at first, but this is on the easiest path to implement pattern-matching compilation.

### CODE REVIEW

**Comment by gasche** [comment]
This PR is now complete and (now that #9 was merged) ready for review.

**Comment by gasche** [comment]
Well "complete": there is more we could do:
- in the compilation of functions, we could generate the argument-related code during the lowering pass instead of at codegen-time
- we could work more to separate the two passes, they are currently intertwined

but I decided to stop here because the bulk of the work is done, and in particular this is more than enough to start with pattern-matching compilation.

**Comment by gasche** [comment]
Ideally, if we pushed this lowering pass to its limits, we could have a situation where `lower-expr` does not depend on `stacksize`, and `compile-expr` does not depend on `env` and `istail`, which would give a nice separation of concerns between thet two passes. But not in this PR.

**Comment by Ekdohibs** [comment]
Thanks a lot! I also thought about the separation of the two passes, but there is a slight complication: `env` indirectly depends on `stacksize`, in the locations of local variables. Anyway, the PR is good, and I am happy to merge it.

**Comment by gasche** [comment]
These PRs were also an excuse to get a broad look at the compiler codebase.

I noticed something which I found surprising. Because you track the shape of functions in the environment, it is only known for "named" functions, not anonymous functions. This means that `let f ~x ~y ... = .. in ...` works perfectly well, but `(fun ~x ~y -> ...)` may not work in surprising ways as its "shape" information is not available, but also for example `let x = (let f ~x ~y = .. in f) in ..` will not behave as expected.

I think that assuming named functions is reasonable, and losing information when "leaking" a function name into another context is also a limitation that we can have, but maybe we should not allow labels on anonymous functions, and raise a warning/error when a function is applied with labels but no shape information is available. (We may have this warning/error already, I must admit that I was too scared to look into the `align-args` implementation so I just avoided it completely.)

**Comment by gasche** [comment]
We could also warn when a function with a non-trivial shape is "leaked" (used as a variable in another place than an application site), to force users to manually eta-expand into a non-labelled version.

**Comment by Ekdohibs** [comment]
There is no warning for now when a non-trivial shape is leaked, unfortunately, although this is on my to-do list. Computing better shapes was the reason for the special-case in `let`-bound function definitions, and the collapse of multiple `'ELambda` expressions into one, by the way.
I think the best thing to do would be to just completely disallow labelled arguments (raising an error) when they do not correspond to a variable with known shape information.

**Pull request merged**
